### ISSUE TITLE
Merge pull request for local-exec environment variables

### ISSUE THREAD

**Issue by bacoboy** [terraform-providers/terraform-provider-local#4]
Looks like this pull request for environment variables never got merged into the local provider so bumping again here.

https://github.com/hashicorp/terraform/pull/13880

**Comment by apparentlymart** [comment]
Hi @bacoboy!

In spite of the overlapping naming, the `local-exec` provisioner is actually not part of this provider since provisioners are a separate concept from providers at this time.

With that said, I'll leave a note on the other issue since you're right that it's been unattended for far too long.

**Comment by bacoboy** [comment]
Yea you are right.  I think I was looking for a way to use credentials from an assumed role from an aws provider in a local-exec call to the CLI (for where terraform has a gap -- like injecting initial steps into emr_create_cluster (see https://github.com/terraform-providers/terraform-provider-aws/issues/1593).
